name: deploy

on:
 push:
  branches:
      - action

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: action/chekout@v2
      - uses: action/setup-node@v1
        with:
          node-version: '16.x'
      - name: Build wep-app
        run: |
          npm ci
          npm run build
      -name: Deploy to gh-pages
       uses: peaceiris/action-gh-pages@v2
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build