name: Lighthouse CI
on: [push]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.20

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run Lighthouse CI
      run: | 
        npm run lhci
        npx lighthouse https://pdhenrique.github.io/lhciProj/build --score=90--quiet
     
      env:
        LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
